common: &default_settings
  license_key: <%= ENV['NEWRELIC_LICENSE_KEY'] %>

  app_name: '<%= app_name %>'
  monitor_mode: true
  developer_mode: false
  log_level: info
  ssl: false

development:
  <<: *default_settings
  monitor_mode: false
  developer_mode: true

test:
  <<: *default_settings
  monitor_mode: false

staging:
  <<: *default_settings
  app_name: '<%= app_name %> (Staging)'
  monitor_mode: true

production:
  <<: *default_settings
  monitor_mode: true
